# Generated by Django 3.0.5 on 2023-09-12 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='region',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
