# Generated by Django 3.0.5 on 2023-09-12 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20230912_1132'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='region',
            new_name='denominacion',
        ),
    ]
